'use strict';

// proceedingTypes values:
//   []                    — applies to all matter types (default)
//   ['probate']           — probate only (court-filing procedures); hidden for trust-only matters
//   ['testate']           — testate probate only
//   ['intestate']         — intestate probate only
//   ['trust']             — shown whenever hasTrust: true (includes trust-only and probate+trust)
//   ['probate_and_trust'] — shown whenever hasTrust: true (same as 'trust' for filtering purposes)
// Note: valid proceedingType values are "testate" | "intestate" | null (trust-only/unknown).
//       "trust" is NOT a valid proceedingType value; it appears only in this proceedingTypes filter array.

const TASK_PHASES = [
  {
    id: 'initial_administration',
    label: 'Initial Administration',
    tasks: [
      { id: 'task_001', label: 'Obtain certified copies of death certificate (10-15)', states: ['MA','RI'], conditions: [] },
      { id: 'task_002', label: 'Confirm sufficient death certificates received', states: ['MA','RI'], conditions: [] },
      { id: 'task_003', label: 'Locate and secure original will and estate planning documents', states: ['MA','RI'], conditions: ['isTestate'] },
      { id: 'task_004', label: 'Review all planning documents including spouse documents', states: ['MA','RI'], conditions: [] },
      { id: 'task_005', label: 'Determine informal vs formal probate', states: ['MA'], conditions: [], proceedingTypes: ['probate'] },
      { id: 'task_006', label: 'Determine whether supervised administration is needed', states: ['MA'], conditions: [], proceedingTypes: ['probate'] },
      { id: 'task_007', label: 'File will with probate court', states: ['MA','RI'], conditions: ['isTestate'], proceedingTypes: ['probate'], autoGenerates: 'letter_file_will' },
      { id: 'task_008', label: 'File petition with certified death certificate and filing fee', states: ['MA','RI'], conditions: [], proceedingTypes: ['probate'] },
      { id: 'task_009', label: 'Send DMA notice by certified mail', states: ['MA'], conditions: [], proceedingTypes: ['probate'], deadline: 'dmaNotice' },
      { id: 'task_010', label: 'Obtain assents, renunciations, and nominations (MPC 455)', states: ['MA'], conditions: [], proceedingTypes: ['probate'] },
      { id: 'task_011', label: 'File bond with probate court', states: ['MA','RI'], conditions: [], proceedingTypes: ['probate'] },
      { id: 'task_012', label: 'File military affidavit if all interested persons have not assented', states: ['MA'], conditions: [], proceedingTypes: ['probate'] },
      { id: 'task_013', label: 'Publish notice to creditors in local newspaper', states: ['MA','RI'], conditions: [], proceedingTypes: ['probate'] },
      { id: 'task_014', label: 'Notify known creditors by certified mail', states: ['MA','RI'], conditions: [], autoGenerates: 'creditor_notice' },
      { id: 'task_015', label: 'File affidavit of publication with probate court', states: ['RI'], conditions: [], proceedingTypes: ['probate'] },
      { id: 'task_016', label: 'Notify Attorney General if charitable bequests or no known heirs', states: ['MA'], conditions: ['hasCharitableBequests'], proceedingTypes: ['probate'] },
      { id: 'task_017', label: 'Search UCC filings for liens', states: ['MA','RI'], conditions: [] },
      { id: 'task_018', label: 'Search unclaimed property in all states where decedent lived', states: ['MA','RI'], conditions: [] },
      { id: 'task_019', label: 'Request credit report on decedent', states: ['MA','RI'], conditions: [] },
      { id: 'task_020', label: 'Input estate questionnaire information into system', states: ['MA','RI'], conditions: [] },
      { id: 'task_021', label: 'Review all tax filing requirements and determine deadlines', states: ['MA','RI'], conditions: [] },
      { id: 'task_022', label: 'Calendar all important dates', states: ['MA','RI'], conditions: [] },
      { id: 'task_023', label: 'Evaluate immediate needs of any closely held business', states: ['MA','RI'], conditions: ['hasBusinessInterests'] },
      { id: 'task_024', label: 'Determine cash needs for estate expenses and liabilities', states: ['MA','RI'], conditions: [] },
      { id: 'task_025', label: 'Obtain EIN for estate', states: ['MA','RI'], conditions: [], autoGenerates: 'letter_irs_ein_confirmation' },
      { id: 'task_026', label: "Obtain EIN for decedent's revocable trust if any", states: ['MA','RI'], conditions: ['hasTrust'] },
      { id: 'task_027', label: 'File IRS Form 56 — Notice of Fiduciary Relationship', states: ['MA','RI'], conditions: [], autoGenerates: 'letter_irs_form56' },
      { id: 'task_028', label: "Gather decedent's prior income tax returns", states: ['MA','RI'], conditions: [] },
      { id: 'task_029', label: 'Consider Section 645 election to treat revocable trust as part of estate', states: ['MA','RI'], conditions: ['hasTrust'] },
      { id: 'task_030', label: 'Consider fiscal year selection for estate', states: ['MA','RI'], conditions: [] },
      { id: 'task_031', label: 'Determine whether to join surviving spouse in filing joint return', states: ['MA','RI'], conditions: ['hasSpouse'] },
      { id: 'task_032', label: 'Open estate checking account', states: ['MA','RI'], conditions: [] },
      { id: 'task_033', label: 'Notify all banks and financial institutions of death', states: ['MA','RI'], conditions: [] },
      { id: 'task_034', label: 'Collect life insurance proceeds payable to estate', states: ['MA','RI'], conditions: ['hasLifeInsurance'] },
      { id: 'task_035', label: 'File for pension payments and annuity benefits', states: ['MA','RI'], conditions: ['hasRetirementAccounts'] },
      { id: 'task_036', label: 'Update homeowners insurance to name PR and devisees as insured', states: ['MA','RI'], conditions: ['hasRealEstate'] },
      { id: 'task_037', label: 'Consider whether ancillary administration is needed', states: ['MA','RI'], conditions: ['hasOutOfStateProperty'] },
      { id: 'task_038', label: 'Change dividend mailing address for securities', states: ['MA','RI'], conditions: ['hasInvestmentAccounts'] },
      { id: 'task_039', label: 'Review any leases held by decedent and notify lessors', states: ['MA','RI'], conditions: [] },
      { id: 'task_040', label: 'Notify Social Security Administration of death', states: ['MA','RI'], conditions: [], autoGenerates: 'letter_death_notification_generic' },
      { id: 'task_041', label: 'Apply for Social Security death benefits or veterans benefits', states: ['MA','RI'], conditions: [] },
      { id: 'task_042', label: 'Request final paycheck and employment death benefits', states: ['MA','RI'], conditions: [] },
      { id: 'task_043', label: 'Notify postal service regarding forwarding address', states: ['MA','RI'], conditions: [] },
      { id: 'task_044', label: 'Send death notification to appropriate entities', states: ['MA','RI'], conditions: [], autoGenerates: 'letter_death_notification_generic' },
      { id: 'task_045', label: 'Notify motor vehicle insurance carrier of death', states: ['MA','RI'], conditions: ['hasVehicles'] },
      { id: 'task_046', label: 'Notify property insurance carrier of death', states: ['MA','RI'], conditions: ['hasRealEstate'] },
      { id: 'task_047', label: 'File life insurance claims for estate-payable policies', states: ['MA','RI'], conditions: ['hasLifeInsurance'] },
      { id: 'task_048', label: 'Secure real estate and personal property', states: ['MA','RI'], conditions: ['hasRealEstate'] },
      { id: 'task_049', label: 'Prepare and send initial client engagement letter', states: ['MA','RI'], conditions: [], autoGenerates: 'initial_client' },
      { id: 'task_050', label: 'Send initial correspondence to beneficiaries with W-9', states: ['MA','RI'], conditions: [], autoGenerates: 'heir_notice' },
      { id: 'task_051', label: 'Prepare authorization to retain accountant', states: ['MA','RI'], conditions: [] },
      { id: 'task_052', label: 'Prepare authorization to retain appraiser', states: ['MA','RI'], conditions: [] },
      { id: 'task_053', label: 'Prepare authorization to retain real estate attorney', states: ['MA','RI'], conditions: ['hasRealEstate'] },
      { id: 'task_054', label: 'Confirm fiduciary compensation arrangement', states: ['MA','RI'], conditions: [] },
      { id: 'task_055', label: 'Conduct initial administration meeting with client', states: ['MA','RI'], conditions: [] },
      { id: 'task_056', label: 'Calendar follow-up meetings', states: ['MA','RI'], conditions: [] },
      { id: 'task_057', label: 'Prepare and file disclaimers if applicable', states: ['MA','RI'], conditions: [], deadline: 'disclaimer_deadline' },
      { id: 'task_058', label: 'Publish informal notice MPC 551 within 30 days of allowance', states: ['MA'], conditions: [], proceedingTypes: ['probate'], deadline: 'informal_publication' },
    ],
  },
  {
    id: 'asset_tracking',
    label: 'Asset Tracking & Inventory',
    tasks: [
      { id: 'task_101', label: 'Update asset information in system', states: ['MA','RI'], conditions: [] },
      { id: 'task_102', label: 'Update liability information in system', states: ['MA','RI'], conditions: [] },
      { id: 'task_103', label: 'Arrange professional appraisal of real estate', states: ['MA','RI'], conditions: ['hasRealEstate'] },
      { id: 'task_104', label: 'Arrange professional appraisal of tangible personal property', states: ['MA','RI'], conditions: ['hasPersonalProperty'] },
      { id: 'task_105', label: 'Arrange appraisal of closely held business interest', states: ['MA','RI'], conditions: ['hasBusinessInterests'] },
      { id: 'task_106', label: 'Request date-of-death valuations for all financial accounts', states: ['MA','RI'], conditions: [] },
      { id: 'task_107', label: 'Request Form 712 for each life insurance policy', states: ['MA','RI'], conditions: ['hasLifeInsurance'] },
      { id: 'task_108', label: 'Input final asset values as of date of death', states: ['MA','RI'], conditions: [] },
      { id: 'task_109', label: 'Evaluate whether alternate valuation date values are needed', states: ['MA','RI'], conditions: ['grossEstateOverFederalThreshold'] },
      { id: 'task_110', label: 'Coordinate basis adjustment with financial institutions', states: ['MA','RI'], conditions: [] },
      { id: 'task_111', label: 'Determine which liabilities pass with asset vs paid by estate', states: ['MA','RI'], conditions: [] },
      { id: 'task_112', label: 'Transfer motor vehicle titles', states: ['MA','RI'], conditions: ['hasVehicles'], deadline: 'inventory' },
      { id: 'task_113', label: 'File inventory with probate court under oath', states: ['MA','RI'], conditions: [], proceedingTypes: ['probate'], deadline: 'inventory', autoGenerates: 'inventory_cover' },
      { id: 'task_114', label: 'Prepare letters of instruction for assets passing to trust', states: ['MA','RI'], conditions: ['hasTrust'] },
      { id: 'task_115', label: 'Prepare letters of instruction for each financial account transfer', states: ['MA','RI'], conditions: [], autoGenerates: 'asset_inquiry' },
      { id: 'task_116', label: 'Prepare letter of instruction for real property transfer', states: ['MA','RI'], conditions: ['hasRealEstate'] },
      { id: 'task_117', label: 'Prepare letter of instruction for retirement account', states: ['MA','RI'], conditions: ['hasRetirementAccounts'] },
      { id: 'task_118', label: 'Evaluate each asset for liquidation vs distribution', states: ['MA','RI'], conditions: [] },
      { id: 'task_119', label: 'Determine preliminary asset allocations', states: ['MA','RI'], conditions: [] },
      { id: 'task_120', label: 'Obtain releases of estate tax lien on tangibles before distribution', states: ['MA','RI'], conditions: ['grossEstateOverMAThreshold'] },
    ],
  },
  {
    id: 'ongoing_administration',
    label: 'Ongoing Administration',
    tasks: [
      { id: 'task_201', label: 'Pay funeral bill and other preferred claims', states: ['MA','RI'], conditions: [] },
      { id: 'task_202', label: 'Monitor and manage creditor claims', states: ['MA','RI'], conditions: [] },
      { id: 'task_203', label: 'Disallow doubtful creditor claims', states: ['MA','RI'], conditions: [] },
      { id: 'task_204', label: 'Assess estate solvency and declare insolvent if necessary', states: ['MA','RI'], conditions: [] },
      { id: 'task_205', label: 'Manage estate investments prudently', states: ['MA','RI'], conditions: [] },
      { id: 'task_206', label: 'Send status update letter to beneficiaries', states: ['MA','RI'], conditions: [], autoGenerates: 'status_update' },
      { id: 'task_207', label: 'Creditor claim deadline — MA: 1 year from death', states: ['MA'], conditions: [], proceedingTypes: ['probate'], deadline: 'creditor_claim_period' },
      { id: 'task_208', label: 'Creditor claim deadline — RI: 6 months from first publication', states: ['RI'], conditions: [], proceedingTypes: ['probate'], deadline: 'creditor_claim_period' },
      { id: 'task_209', label: 'Surviving spouse election against will — deadline', states: ['MA','RI'], conditions: ['hasSpouse','isTestate'], deadline: 'spousal_election' },
      { id: 'task_210', label: 'Family allowance determination', states: ['MA','RI'], conditions: ['hasSpouse'] },
      { id: 'task_211', label: 'Pay general pecuniary devises before interest begins to run', states: ['MA'], conditions: ['isTestate'], deadline: 'pecuniary_devise_interest' },
      { id: 'task_212', label: 'Revalue assets at alternate valuation date if applicable', states: ['MA','RI'], conditions: ['grossEstateOverFederalThreshold'], deadline: 'alternate_valuation_date' },
      { id: 'task_213', label: 'Handle subtrust administration if applicable', states: ['MA','RI'], conditions: ['hasTrust'] },
      { id: 'task_214', label: 'Prepare distribution documents for interim advancements', states: ['MA','RI'], conditions: [] },
      { id: 'task_215', label: 'Confirm satisfaction of all estate expenses and liabilities', states: ['MA','RI'], conditions: [] },
    ],
  },
  {
    id: 'tax_filings',
    label: 'Tax Filings',
    tasks: [
      { id: 'task_301', label: "File decedent's final Form 1040 federal income tax return", states: ['MA','RI'], conditions: [], deadline: 'final_1040_due' },
      { id: 'task_302', label: 'File final state income tax return', states: ['MA','RI'], conditions: [] },
      { id: 'task_303', label: 'File estate fiduciary income tax return — Form 1041', states: ['MA','RI'], conditions: [], deadline: 'fiduciary_income_tax' },
      { id: 'task_304', label: 'File state fiduciary income tax return', states: ['MA','RI'], conditions: [] },
      { id: 'task_305', label: 'Prepare Schedule K-1 for each beneficiary', states: ['MA','RI'], conditions: [] },
      { id: 'task_306', label: 'Extend tax filing deadlines if needed — Form 4768', states: ['MA','RI'], conditions: [], deadline: 'extension_deadline' },
      { id: 'task_307', label: 'Prepare and file Form 706 federal estate tax return', states: ['MA','RI'], conditions: ['grossEstateOverFederalThreshold'], deadline: 'estate_tax_return' },
      { id: 'task_308', label: 'Prepare and file MA Form M-706 state estate tax return', states: ['MA'], conditions: ['grossEstateOverMAThreshold'], deadline: 'estate_tax_return' },
      { id: 'task_309', label: 'Prepare and file RI Form RI-706 state estate tax return', states: ['RI'], conditions: ['grossEstateOverRIThreshold'], deadline: 'estate_tax_return' },
      { id: 'task_310', label: 'Prepare Form 8971 and Schedule A per beneficiary', states: ['MA','RI'], conditions: ['grossEstateOverFederalThreshold'] },
      { id: 'task_311', label: 'Request IRS closing letter', states: ['MA','RI'], conditions: ['grossEstateOverFederalThreshold'], deadline: 'irs_closing_letter_request' },
      { id: 'task_312', label: 'File federal closing letter with MA Estate Tax Bureau within 60 days', states: ['MA'], conditions: ['grossEstateOverMAThreshold'] },
      { id: 'task_313', label: 'Make estimated tax payments on estate income', states: ['MA','RI'], conditions: [] },
      { id: 'task_314', label: 'Determine whether to waive or claim fiduciary fees', states: ['MA','RI'], conditions: [] },
      { id: 'task_315', label: 'Consider IRC Section 6166 installment election for estate tax', states: ['MA','RI'], conditions: ['hasBusinessInterests','grossEstateOverFederalThreshold'] },
      { id: 'task_316', label: 'Consider IRC Section 303 redemption to pay estate taxes', states: ['MA','RI'], conditions: ['hasBusinessInterests'] },
    ],
  },
  {
    id: 'final_administration',
    label: 'Final Administration',
    tasks: [
      { id: 'task_401', label: 'Confirm creditor claim period has expired', states: ['MA','RI'], conditions: [], deadline: 'creditor_claim_period' },
      { id: 'task_402', label: 'File RI Section 33-11-5.1 affidavit of compliance with creditor notice', states: ['RI'], conditions: [], proceedingTypes: ['probate'] },
      { id: 'task_403', label: 'Confirm all estate taxes paid or cleared', states: ['MA','RI'], conditions: [] },
      { id: 'task_404', label: 'Record release of estate tax lien with registry of deeds', states: ['MA','RI'], conditions: ['hasRealEstate','grossEstateOverMAThreshold'] },
      { id: 'task_405', label: 'Petition for license to sell real estate if needed', states: ['MA','RI'], conditions: ['hasRealEstate'] },
      { id: 'task_406', label: 'Determine final asset allocation', states: ['MA','RI'], conditions: [] },
      { id: 'task_407', label: 'Prepare proposed distribution plan for each beneficiary', states: ['MA','RI'], conditions: [], autoGenerates: 'distribution' },
      { id: 'task_408', label: 'Prepare final account Schedules A through D', states: ['MA','RI'], conditions: [] },
      { id: 'task_409', label: 'File petition for allowance of final account with probate court', states: ['MA','RI'], conditions: [], proceedingTypes: ['probate'] },
      { id: 'task_410', label: 'Advertise hearing on final account', states: ['MA','RI'], conditions: [], proceedingTypes: ['probate'] },
      { id: 'task_411', label: 'Give 10 days notice by mail to all interested parties of hearing', states: ['MA','RI'], conditions: [], proceedingTypes: ['probate'] },
      { id: 'task_412', label: 'Attend hearing and obtain allowance of account', states: ['MA','RI'], conditions: [], proceedingTypes: ['probate'] },
      { id: 'task_413', label: 'File MA closing statement MPC 850 or small estate MPC 851', states: ['MA'], conditions: [], proceedingTypes: ['probate'] },
      { id: 'task_414', label: 'File MA petition for order of complete settlement MPC 855', states: ['MA'], conditions: [], proceedingTypes: ['probate'] },
      { id: 'task_415', label: 'Notify surety of allowance of petition for complete settlement', states: ['MA'], conditions: [], proceedingTypes: ['probate'] },
      { id: 'task_416', label: 'Make final distributions to all beneficiaries', states: ['MA','RI'], conditions: [], autoGenerates: 'distribution' },
      { id: 'task_417', label: 'Obtain signed receipts and release agreements from all distributees', states: ['MA','RI'], conditions: [] },
      { id: 'task_418', label: 'Notify beneficiaries of tax cost basis of inherited property', states: ['MA','RI'], conditions: [] },
      { id: 'task_419', label: 'File final fiduciary income tax returns', states: ['MA','RI'], conditions: [] },
      { id: 'task_420', label: 'Close estate bank account after final distributions', states: ['MA','RI'], conditions: [] },
      { id: 'task_421', label: 'Discharge executor/administrator bond', states: ['MA','RI'], conditions: [], proceedingTypes: ['probate'] },
      { id: 'task_422', label: 'Terminate administration trust if applicable', states: ['MA','RI'], conditions: ['hasTrust'] },
      { id: 'task_423', label: 'Send letter to beneficiaries closing administration', states: ['MA','RI'], conditions: [], autoGenerates: 'closing' },
      { id: 'task_424', label: 'Send letter to client with notice of close of probate', states: ['MA','RI'], conditions: [], autoGenerates: 'closing' },
      { id: 'task_425', label: 'Confirm all asset transfers completed', states: ['MA','RI'], conditions: [] },
      { id: 'task_426', label: 'Close matter in system', states: ['MA','RI'], conditions: [] },
    ],
  },
  {
    id: 'trust_administration',
    label: 'Trust Administration',
    tasks: [
      { id: 'task_501', label: 'Review trust document and identify all trustee duties and powers', states: ['MA','RI'], conditions: ['hasTrust'], proceedingTypes: ['trust'] },
      { id: 'task_502', label: 'Send notice of successor trustee appointment to all beneficiaries', states: ['MA','RI'], conditions: ['hasTrust'], proceedingTypes: ['trust'], deadline: 'trustee_beneficiary_notice', autoGenerates: 'letter_trustee_notice_to_beneficiaries' },
      { id: 'task_503', label: 'Prepare and record affidavit of successor trustee', states: ['MA','RI'], conditions: ['hasTrust'], proceedingTypes: ['trust'], autoGenerates: 'letter_trustee_affidavit' },
      { id: 'task_504', label: 'Prepare certification of trust for financial institutions', states: ['MA','RI'], conditions: ['hasTrust'], proceedingTypes: ['trust'], autoGenerates: 'letter_certification_of_trust' },
      { id: 'task_505', label: 'Open trust checking account in trustee name', states: ['MA','RI'], conditions: ['hasTrust'], proceedingTypes: ['trust'] },
      { id: 'task_506', label: 'Transfer financial accounts into trust (retitle to trustee)', states: ['MA','RI'], conditions: ['hasTrust'], proceedingTypes: ['trust'] },
      { id: 'task_507', label: 'Transfer real property to trustee via deed', states: ['MA','RI'], conditions: ['hasTrust','hasRealEstate'], proceedingTypes: ['trust'] },
      { id: 'task_508', label: 'Fund trust with pour-over assets from probate estate', states: ['MA','RI'], conditions: ['hasTrust'], proceedingTypes: ['probate_and_trust'] },
      { id: 'task_509', label: 'File IRS Form 56 for trust — Notice of Fiduciary Relationship', states: ['MA','RI'], conditions: ['hasTrust'], proceedingTypes: ['trust'] },
      { id: 'task_510', label: 'Obtain or confirm EIN for trust', states: ['MA','RI'], conditions: ['hasTrust'], proceedingTypes: ['trust'] },
      { id: 'task_511', label: 'Consider and file Section 645 election if eligible', states: ['MA','RI'], conditions: ['hasTrust'], proceedingTypes: ['probate_and_trust'] },
      { id: 'task_512', label: 'Prepare initial trust accounting (Schedule A through D)', states: ['MA','RI'], conditions: ['hasTrust'], proceedingTypes: ['trust'], autoGenerates: 'letter_trust_accounting' },
      { id: 'task_513', label: 'Distribute trust income to beneficiaries as required by trust', states: ['MA','RI'], conditions: ['hasTrust'], proceedingTypes: ['trust'] },
      { id: 'task_514', label: 'Handle required minimum distributions from inherited IRAs', states: ['MA','RI'], conditions: ['hasTrust','hasRetirementAccounts'], proceedingTypes: ['trust'] },
      { id: 'task_515', label: 'Review and document trust investment policy and decisions', states: ['MA','RI'], conditions: ['hasTrust'], proceedingTypes: ['trust'] },
      { id: 'task_516', label: 'Send annual trust accounting to all beneficiaries', states: ['MA','RI'], conditions: ['hasTrust'], proceedingTypes: ['trust'], autoGenerates: 'letter_trust_accounting' },
      { id: 'task_517', label: 'Review spendthrift and distribution restriction provisions', states: ['MA','RI'], conditions: ['hasTrust'], proceedingTypes: ['trust'] },
      { id: 'task_518', label: 'Process and document discretionary distribution requests', states: ['MA','RI'], conditions: ['hasTrust'], proceedingTypes: ['trust'] },
      { id: 'task_519', label: 'Prepare and file trust income tax returns — Form 1041', states: ['MA','RI'], conditions: ['hasTrust'], proceedingTypes: ['trust'], deadline: 'trust_accounting' },
      { id: 'task_520', label: 'Review trust termination conditions and timeline', states: ['MA','RI'], conditions: ['hasTrust'], proceedingTypes: ['trust'] },
      { id: 'task_521', label: 'Prepare final trust accounting for termination', states: ['MA','RI'], conditions: ['hasTrust'], proceedingTypes: ['trust'], autoGenerates: 'letter_trust_termination' },
      { id: 'task_522', label: 'Make final trust distributions and terminate trust', states: ['MA','RI'], conditions: ['hasTrust'], proceedingTypes: ['trust'] },
    ],
  },
];

function getAllTasks() {
  return TASK_PHASES.flatMap(phase =>
    phase.tasks.map(t => ({ ...t, phaseId: phase.id, phaseLabel: phase.label }))
  );
}

// Maps each kanban stage to the task IDs that belong to that stage.
const STAGE_TASK_MAPPING = {
  PETITION_PREP: [
    'task_001', 'task_002', 'task_003', 'task_004', 'task_005',
    'task_006', 'task_007', 'task_008', 'task_009', 'task_010',
    'task_011', 'task_012', 'task_013', 'task_014', 'task_016',
    'task_017', 'task_018', 'task_019', 'task_020', 'task_021',
    'task_022', 'task_024', 'task_049', 'task_050',
  ],
  FILED: [
    'task_015', 'task_023', 'task_040', 'task_041', 'task_042',
    'task_043', 'task_044', 'task_045', 'task_046', 'task_047',
    'task_048', 'task_051', 'task_052', 'task_053', 'task_054',
    'task_055', 'task_056', 'task_057', 'task_058',
  ],
  APPOINTED: [
    'task_025', 'task_026', 'task_027', 'task_028', 'task_029',
    'task_030', 'task_031', 'task_032', 'task_033', 'task_034',
    'task_035', 'task_036', 'task_037', 'task_038', 'task_039',
  ],
  IN_ADMINISTRATION: [
    'task_101', 'task_102', 'task_103', 'task_104', 'task_105',
    'task_106', 'task_107', 'task_108', 'task_109', 'task_110',
    'task_111', 'task_112', 'task_113', 'task_114', 'task_115',
    'task_116', 'task_117', 'task_118', 'task_119', 'task_120',
    'task_201', 'task_202', 'task_203', 'task_204', 'task_205',
    'task_206', 'task_207', 'task_208', 'task_209', 'task_210',
    'task_211', 'task_212', 'task_213', 'task_214', 'task_215',
    'task_501', 'task_502', 'task_503', 'task_504', 'task_505',
    'task_506', 'task_507', 'task_508', 'task_509', 'task_510',
    'task_511', 'task_512', 'task_513', 'task_514', 'task_515',
  ],
  CLOSING_PREP: [
    'task_301', 'task_302', 'task_303', 'task_304', 'task_305',
    'task_306', 'task_307', 'task_308', 'task_309', 'task_310',
    'task_311', 'task_312', 'task_313', 'task_314', 'task_315',
    'task_316', 'task_401', 'task_402', 'task_403', 'task_404',
    'task_405', 'task_406', 'task_407', 'task_408', 'task_409',
    'task_410', 'task_411', 'task_412', 'task_413', 'task_414',
    'task_415', 'task_516', 'task_517', 'task_518', 'task_519',
    'task_520', 'task_521', 'task_522',
  ],
  CLOSED: [],
};

const PLANNING_STAGES = [
  { id: 'INTAKE',    label: 'Intake'    },
  { id: 'DRAFTING',  label: 'Drafting'  },
  { id: 'REVIEW',    label: 'Review'    },
  { id: 'SIGNING',   label: 'Signing'   },
  { id: 'COMPLETE',  label: 'Complete'  },
];
const PLANNING_STAGE_IDS = new Set(PLANNING_STAGES.map(s => s.id));
const ADMIN_STAGE_IDS    = new Set(Object.keys(STAGE_TASK_MAPPING));

module.exports = { TASK_PHASES, getAllTasks, STAGE_TASK_MAPPING, PLANNING_STAGES, PLANNING_STAGE_IDS, ADMIN_STAGE_IDS };
