'use strict';

/**
 * exportToProduction.js
 *
 * Reads all local JSON data files and writes a production_seed.sql file
 * containing idempotent INSERT statements for every record.
 *
 * Usage:
 *   node scripts/exportToProduction.js
 *
 * Then import to Render Postgres:
 *   psql "$DATABASE_URL" -f scripts/production_seed.sql
 */

const fs   = require('fs');
const path = require('path');

const DATA_DIR  = path.join(__dirname, '../data');
const OUT_FILE  = path.join(__dirname, 'production_seed.sql');
const MAX_AUDIT = 500;

// ── helpers ────────────────────────────────────────────────────────────────────

function readJson(filename, fallback) {
  const p = path.join(DATA_DIR, filename);
  if (!fs.existsSync(p)) return fallback;
  try { return JSON.parse(fs.readFileSync(p, 'utf8')); }
  catch (e) { console.warn(`  WARNING: could not parse ${filename}:`, e.message); return fallback; }
}

// Escape a value for SQL: null → NULL, strings → single-quoted with escaping
function sql(v) {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'boolean') return v ? 'TRUE' : 'FALSE';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'object') return `'${JSON.stringify(v).replace(/'/g, "''")}'`;
  return `'${String(v).replace(/'/g, "''")}'`;
}

// For JSONB columns — always stringify objects
function sqlJson(v) {
  if (v === null || v === undefined) return 'NULL';
  return `'${JSON.stringify(v).replace(/'/g, "''")}'`;
}

// For TEXT columns
function sqlText(v) {
  if (v === null || v === undefined) return 'NULL';
  return `'${String(v).replace(/'/g, "''")}'`;
}

// Timestamp: accept ISO string or Date; return SQL literal or NULL
function sqlTs(v) {
  if (!v) return 'NULL';
  return `'${String(v).replace(/'/g, "''")}'`;
}

const lines = [];
function emit(...parts) { lines.push(parts.join('')); }

// ── header ────────────────────────────────────────────────────────────────────

emit('-- production_seed.sql');
emit('-- Generated by scripts/exportToProduction.js on ', new Date().toISOString());
emit('-- Run with: psql "$DATABASE_URL" -f scripts/production_seed.sql');
emit('--');
emit('-- All statements use ON CONFLICT DO NOTHING — safe to re-run.');
emit('');
emit('BEGIN;');
emit('');

// ── users ────────────────────────────────────────────────────────────────────

const userData = readJson('users.json', { users: [] });
const users    = userData.users || [];

emit('-- ── users (', users.length, ' records) ─────────────────────────────────────');
for (const u of users) {
  emit(
    `INSERT INTO users (id, name, email, role, password_hash, created_at, last_login, active, must_change_password) VALUES (`,
    `${sqlText(u.id)}, `,
    `${sqlText(u.name)}, `,
    `${sqlText(u.email)}, `,
    `${sqlText(u.role)}, `,
    `${sqlText(u.passwordHash)}, `,
    `${sqlTs(u.createdAt  || new Date().toISOString())}, `,
    `${sqlTs(u.lastLogin)}, `,
    `${u.active !== false ? 'TRUE' : 'FALSE'}, `,
    `${u.mustChangePassword !== false ? 'TRUE' : 'FALSE'}`,
    `) ON CONFLICT (id) DO NOTHING;`
  );
}
emit('');

// ── matter_admin + matter_tasks ───────────────────────────────────────────────

const adminData = readJson('administration.json', {});

// Stage normalization (mirrors server.js)
const STAGE_NORMALIZE = {
  'INTAKE':            'PETITION_PREP',
  'PETITION PREP':     'PETITION_PREP',
  'IN ADMINISTRATION': 'IN_ADMINISTRATION',
  'CLOSING PREP':      'CLOSING_PREP',
};
// Planning stage IDs that should be preserved as-is
const PLANNING_STAGES = new Set(['INTAKE','DRAFTING','REVIEW','SIGNING','COMPLETE','CLOSED_PLANNING']);

function normalizeStage(s) {
  if (!s) return 'PETITION_PREP';
  if (PLANNING_STAGES.has(s)) return s;
  return STAGE_NORMALIZE[s] || s;
}

const matters   = Object.entries(adminData);
let taskTotal   = 0;

emit('-- ── matter_admin (', matters.length, ' records) ─────────────────────────────');
for (const [matterId, rec] of matters) {
  const stage         = normalizeStage(rec.stage);
  const keyDates      = rec.keyDates      || {};
  const notes         = rec.notes         || null;
  const mtoJSON       = rec.matterTypeOverrides  || {};
  const taJSON        = rec.taskAssignments       || {};
  const staffJSON     = rec.staff                 || [];
  const customNotes   = typeof rec.customNotes === 'string' ? rec.customNotes : '';
  const pending       = rec.pendingMatterTypeChange || null;
  const savedType     = rec.savedMatterType         || null;

  emit(
    `INSERT INTO matter_admin (matter_id, stage, key_dates, notes, matter_type_overrides, task_assignments, staff, custom_notes, pending_matter_type_change, saved_matter_type) VALUES (`,
    `${sqlText(matterId)}, `,
    `${sqlText(stage)}, `,
    `${sqlJson(keyDates)}, `,
    `${sqlText(notes)}, `,
    `${sqlJson(mtoJSON)}, `,
    `${sqlJson(taJSON)}, `,
    `${sqlJson(staffJSON)}, `,
    `${sqlText(customNotes)}, `,
    `${pending  ? sqlJson(pending)   : 'NULL'}, `,
    `${savedType ? sqlJson(savedType) : 'NULL'}`,
    `) ON CONFLICT (matter_id) DO NOTHING;`
  );
}
emit('');

emit('-- ── matter_tasks (', 'see below', ' records) ──────────────────────────────────');
for (const [matterId, rec] of matters) {
  const tasks = rec.tasks || {};
  for (const [taskId, val] of Object.entries(tasks)) {
    let status, prevStatus, setDate, setBy, taskNotes;
    if (typeof val === 'string') {
      status = val; prevStatus = null; setDate = null; setBy = null; taskNotes = null;
    } else if (val && typeof val === 'object') {
      status     = val.status         || 'open';
      prevStatus = val.previousStatus || null;
      setDate    = val.setDate        || null;
      setBy      = val.setBy          || null;
      taskNotes  = val.notes          || null;
    } else {
      continue;
    }
    emit(
      `INSERT INTO matter_tasks (matter_id, task_id, status, previous_status, set_date, set_by, notes) VALUES (`,
      `${sqlText(matterId)}, `,
      `${sqlText(taskId)}, `,
      `${sqlText(status)}, `,
      `${sqlText(prevStatus)}, `,
      `${sqlTs(setDate)}, `,
      `${sqlText(setBy)}, `,
      `${sqlText(taskNotes)}`,
      `) ON CONFLICT (matter_id, task_id) DO NOTHING;`
    );
    taskTotal++;
  }
}
emit('');

// ── flags ─────────────────────────────────────────────────────────────────────

const flags = readJson('flags.json', []);
const flagArr = Array.isArray(flags) ? flags : [];

emit('-- ── flags (', flagArr.length, ' records) ────────────────────────────────────');
for (const f of flagArr) {
  emit(
    `INSERT INTO flags (id, matter_id, matter_name, type, severity, message, raised_at, last_seen_at, acknowledged_at, resolved_at) VALUES (`,
    `${sqlText(f.id)}, `,
    `${sqlText(f.matterId)}, `,
    `${sqlText(f.matterName || null)}, `,
    `${sqlText(f.type)}, `,
    `${sqlText(f.severity)}, `,
    `${sqlText(f.message)}, `,
    `${sqlTs(f.raisedAt       || new Date().toISOString())}, `,
    `${sqlTs(f.lastSeenAt     || null)}, `,
    `${sqlTs(f.acknowledgedAt || null)}, `,
    `${sqlTs(f.resolvedAt     || null)}`,
    `) ON CONFLICT (id) DO NOTHING;`
  );
}
emit('');

// ── audit_events (last MAX_AUDIT) ─────────────────────────────────────────────

const auditData   = readJson('auditLog.json', { events: [] });
const allEvents   = auditData.events || [];
const auditEvents = allEvents.slice(0, MAX_AUDIT);

emit('-- ── audit_events (', auditEvents.length, ' of ', allEvents.length, ' records) ──────────────────');
for (const e of auditEvents) {
  emit(
    `INSERT INTO audit_events (id, timestamp, user_id, user_name, user_role, action, matter_id, matter_name, detail, previous_value, new_value, ip_address, user_agent) VALUES (`,
    `${sqlText(e.id)}, `,
    `${sqlTs(e.timestamp || new Date().toISOString())}, `,
    `${sqlText(e.userId        || null)}, `,
    `${sqlText(e.userName      || null)}, `,
    `${sqlText(e.userRole      || null)}, `,
    `${sqlText(e.action)}, `,
    `${sqlText(e.matterId      || null)}, `,
    `${sqlText(e.matterName    || null)}, `,
    `${sqlText(e.detail        || null)}, `,
    `${sqlText(e.previousValue !== undefined && e.previousValue !== null ? String(e.previousValue) : null)}, `,
    `${sqlText(e.newValue      !== undefined && e.newValue      !== null ? String(e.newValue)      : null)}, `,
    `${sqlText(e.ipAddress     || null)}, `,
    `${sqlText(e.userAgent     || null)}`,
    `) ON CONFLICT (id) DO NOTHING;`
  );
}
emit('');

// ── settings (aiSettings, alertHistory) ──────────────────────────────────────

emit('-- ── settings ───────────────────────────────────────────────────────────────');

const aiSettings = readJson('aiSettings.json', { AI_DEADLINE_ALERTS: true, AI_DOCUMENT_SCANNER: true, AI_EXTRACTION: false });
emit(
  `INSERT INTO settings (key, value) VALUES ('aiSettings', ${sqlJson(aiSettings)}) ON CONFLICT (key) DO UPDATE SET value=EXCLUDED.value;`
);

const alertHistory = readJson('alertHistory.json', {});
emit(
  `INSERT INTO settings (key, value) VALUES ('alertHistory', ${sqlJson(alertHistory)}) ON CONFLICT (key) DO UPDATE SET value=EXCLUDED.value;`
);

const scanHistoryFile = path.join(DATA_DIR, 'scanHistory.json');
if (fs.existsSync(scanHistoryFile)) {
  try {
    const scanHistory = JSON.parse(fs.readFileSync(scanHistoryFile, 'utf8'));
    emit(
      `INSERT INTO settings (key, value) VALUES ('scanHistory', ${sqlJson(scanHistory)}) ON CONFLICT (key) DO UPDATE SET value=EXCLUDED.value;`
    );
  } catch {}
}
emit('');

// ── footer ────────────────────────────────────────────────────────────────────

emit('COMMIT;');
emit('');
emit('-- Done.');

// ── write file ────────────────────────────────────────────────────────────────

fs.writeFileSync(OUT_FILE, lines.join('\n') + '\n');

console.log('Export complete →', path.relative(process.cwd(), OUT_FILE));
console.log('');
console.log('Records exported:');
console.log('  users         :', users.length);
console.log('  matter_admin  :', matters.length);
console.log('  matter_tasks  :', taskTotal);
console.log('  flags         :', flagArr.length);
console.log('  audit_events  :', auditEvents.length);
console.log('  settings keys :', fs.existsSync(path.join(DATA_DIR, 'scanHistory.json')) ? 3 : 2,
            '(aiSettings, alertHistory' + (fs.existsSync(path.join(DATA_DIR, 'scanHistory.json')) ? ', scanHistory' : '') + ')');
console.log('');
console.log('To import to Render Postgres:');
console.log('  psql "$DATABASE_URL" -f scripts/production_seed.sql');
